### ISSUE TITLE
Natural sorting of albums

### ISSUE THREAD

**Issue by pacija** [gs11/sonerezh#3]
Hi,

currently, albums are sorted regularly, so e.g. "compilation vol. 10" comes before "compilation vol. 2".

Would it be too much of a hassle to change it to natural sorting, eg. "compilation vol. 2" comes before "compilation vol. 10"?

Thank you in advance,

**Comment by gs11** [comment]
Without having dug into it, I'd think this would be non-trivial to solve and might impact performance. Maybe possible with regex..

**Comment by MightyCreak** [comment]
In PHP there is [natsort](http://php.net/manual/en/function.natsort.php), but that would indeed be a perf problem since sonerezh would have to get all the album in order to be able to sort them properly, which will obviously be a problem as the library grows.

I haven't seen a MySQL function for that... The only solution I've seen is to add a new column in the table that would define the sort order. I guess this column would be recomputed each time a new album is added.

I'm trying to see how Deezer handles this kind of stuff, it seems that it doesn't care at all (at least in the search): http://www.deezer.com/search/top%20100%2090's/album

Honestly, considering the amount of work or the perf regression that this feature would need, why not renaming your albums with a leading "0" @pacija? like this: "compilation vol. 08", "compilation vol. 09", "compilation vol. 10", ...

Seems like the easiest and cleanest solution, even if it involves changes on the user side. What do you think?

**Comment by pacija** [comment]
@MightyCreak I have resorted to renaming my albums as you suggested. I wanted for my tags to be 100% identical to Discogs, but I realized I also have compilations that have roman numbering :)

Closing,
